/* eslint-disable */
import {
  Button,
  NavBar,
  Icon,
  List,
  Cell,
  CountDown,
  Field,
  RadioGroup,
  Radio,
  Uploader,
  Image as VanImage,
  TreeSelect,
  Col,
  Dialog,
  Toast,
  Tab,
  Tabs,
  Progress,
  Search,
  Checkbox,
  CheckboxGroup,
  DropdownMenu,
  DropdownItem,
  Swipe,
  SwipeItem,
  AddressEdit,
  Switch,
  SwipeCell,
  AddressList,
  ActionSheet,
  Step,
  Steps,
  Stepper,
  Picker,
  Popup
} from "vant";

export default function (app: any) {
  app
    .use(Button)
    .use(NavBar)
    .use(Icon)
    .use(List)
    .use(Cell)
    .use(CountDown)
    .use(Field)
    .use(RadioGroup)
    .use(Radio)
    .use(Uploader)
    .use(VanImage)
    .use(TreeSelect)
    .use(Col)
    .use(Dialog)
    .use(Toast).use(Tab).use(Tabs)
    .use(Progress)
    .use(Toast)
    .use(Tab)
    .use(Tabs)
    .use(Search)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(DropdownMenu)
    .use(DropdownItem)
    .use(Swipe)
    .use(SwipeItem)
    .use(AddressEdit)
    .use(Switch)
    .use(SwipeCell)
    .use(AddressList)
    .use(ActionSheet)
    .use(Step)
    .use(Steps)
    .use(Stepper).use(Picker).use(Popup);
}
